workflows:
  vps-bot-workflow:
    name: VPS Bot Workflow
    instance_type: linux
    environment:
      vars:
        BOT_TOKEN: "7789286725:AAHncH6RSYj5w8uSfNOdzsgHfy7ymiC6-hE"
        ALLOWED_USER_ID: "8003600588"
    scripts:
      - name: Install Python 3.9
        script: |
          # Check if Python 3.9 is installed, if not, install it
          if ! command -v python3.9 &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y python3.9 python3.9-dev python3-pip
          fi
          python3.9 --version
      - name: Install Dependencies
        script: |
          python3.9 -m pip install pyTelegramBotAPI requests
      - name: Run VPS Bot Script
        script: |
          python3.9 vps.py
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
    artifacts:
      - "*.txt"
      - "vps.py"
